using System.Collections.Generic;

namespace Hasse.Web.ApiModels
{
    // ApiModel DTOs are used by ApiController classes and are typically kept in a side-by-side folder
    public class ProjectDTO : CreateProjectDTO
    {
        public List<ToDoItemDTO> Items = new();
        public int Id { get; set; }
    }

    // Creation DTOs should not include an ID if the ID will be generated by the back end
}